<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.9 setup script
 * Date: Sun, 31 May 2015 15:38:44 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: sddb0040106762.cgidb [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'sddb0040105822.cgidb';
$cfg['Servers'][$i]['host'] = 'sddb0040105822.cgidb';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['only_db'] = array('sddb0040105822');

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = true;
$cfg['blowfish_secret'] = '556b2afa5a0908.36710541';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
?>